# Site
#repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: German Smirnov
title: Senior JavaScript developer
email: ledamint@gmail.com
website: github.com/ledamint

# Social links
#twitter_username: facespics
github_username:  ledamint
telegram_username: asd
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: german-smirnov-1b2239157
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
#darkmode: true
# About Section
# about_title: About Me
#about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am a professional software developer. Programming is my favorite hobby which happily also is my work. There you can read about my experience and personal projects.

  I am most skilled in <mark>JavaScript</mark> <mark>TypeScript</mark> <mark>React</mark> <mark>Vue</mark> <mark>NodeJS</mark> <mark>MongoDB</mark> <mark>GraphQL</mark>.

#  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs
#  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#   - Rock climbing
#   - Gaming
#   - Knitting
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
#footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
